server:
  port: 38080
  servlet:
    context-path: /at-api

spring:
  application:
    name: ${artifactId}
  profiles:
    active: master
  jackson:
    date-format:  "yyyy-MM-dd HH:mm"
    time-zone: "GMT+08:00"
    default-property-inclusion: non_empty
